# Generated by Django 2.2.5 on 2019-09-24 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0005_auto_20190924_1126"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTicketTopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=300)),
                (
                    "text_in_ar",
                    models.TextField(max_length=300, verbose_name="Text in arabic"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("text", "text_in_ar")},
        ),
        migrations.CreateModel(
            name="CustomerTicket",
            fields=[
                (
                    "id",
                    django_extensions.db.fields.ShortUUIDField(
                        blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sub_topic", models.CharField(help_text="Topic Name", max_length=300)),
                ("description", models.TextField(max_length=1000)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Open"), (1, "Closed")], default=0
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.CustomerTicketTopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Ticket",
                "verbose_name_plural": "Customer Tickets",
                "ordering": ("-last_updated",),
            },
        ),
    ]
