# Generated by Django 2.2.4 on 2019-08-25 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.file


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0002_auto_20190817_1036"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=144)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=300)),
                (
                    "picture",
                    models.ImageField(
                        default="user/restaurant/food/default.png",
                        upload_to=utils.file.RandomFileName("user/restaurant/food/"),
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("calorie", models.IntegerField()),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="food.FoodCategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodAttributeMatrix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=144)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.FoodAttribute",
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="foodattribute",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.FoodItem"
            ),
        ),
        migrations.CreateModel(
            name="FoodAddOn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=144)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.FoodItem"
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
    ]
