# Generated by Django 2.2.4 on 2019-08-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("food", "0006_auto_20190829_0809")]

    operations = [
        migrations.AddField(
            model_name="foodaddon",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        )
    ]
