# Generated by Django 2.2.4 on 2019-08-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_foodaddon_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodaddon',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item', to='food.FoodItem'),
        ),
    ]
