# Generated by Django 2.2.4 on 2019-09-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20190903_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodattribute',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='foodattributematrix',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
