# Generated by Django 2.2.4 on 2019-09-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_foodattribute_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodattribute',
            name='price',
        ),
    ]
