# Generated by Django 2.2.5 on 2019-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("food", "0014_auto_20190922_1753")]

    operations = [
        migrations.AlterField(
            model_name="foodaddon",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodattribute",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodattributematrix",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
