# Generated by Django 2.2.5 on 2019-10-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("food", "0016_auto_20190923_1542")]

    operations = [
        migrations.AlterModelOptions(
            name="fooditem", options={"ordering": ("-created_at",)}
        )
    ]
