# Generated by Django 2.2.5 on 2019-10-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0018_auto_20191005_0458"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodaddon",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
