# Generated by Django 2.2.5 on 2019-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0019_auto_20191019_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodaddon",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
