# Generated by Django 2.2.5 on 2019-11-12 14:52

from django.db import migrations, models
import utils.file


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20191023_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='picture',
            field=models.ImageField(blank=True, default='user/restaurant/food/default.png', null=True, upload_to=utils.file.RandomFileName('user/restaurant/food/')),
        ),
    ]
