# Generated by Django 2.2.5 on 2019-10-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_auto_20191009_0629"),
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="order_id", new_name="pt_order_id",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_id",
            new_name="pt_transaction_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                default=8, on_delete=django.db.models.deletion.CASCADE, to="order.Order"
            ),
            preserve_default=False,
        ),
    ]
