# Generated by Django 2.2.8 on 2020-03-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_auto_20200330_1521"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoiceitem", name="tax_percentage",),
    ]
