# Generated by Django 2.2.8 on 2020-04-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0009_auto_20200401_0941"),
    ]

    operations = [
        migrations.AlterModelOptions(name="invoice", options={"ordering": ("-id",)},),
    ]
