# Generated by Django 2.2.4 on 2019-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contact", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="contactgroup",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        )
    ]
