# Generated by Django 2.2.5 on 2019-09-29 14:49

from django.db import migrations


def create_misc_for_previous_customers(apps, schema_editor):
    Customer = apps.get_model("customer", "Customer")
    Misc = apps.get_model("customer", "Misc")
    for customer in Customer.objects.all():
        Misc.objects.create(user=customer.user)


class Migration(migrations.Migration):
    dependencies = [("customer", "0002_misc")]

    operations = [migrations.RunPython(create_misc_for_previous_customers)]
