# Generated by Django 2.2.5 on 2019-09-11 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20190911_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fully_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Closed'), (1, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.SmallIntegerField(choices=[(0, 'Pick Up'), (2, 'In House')], help_text='Indicates weather the order is a Pick up order or In House '),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed')], db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='OrderItemInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_invited_by_user', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_invited_user', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_order_item_invites', to='order.OrderItem')),
            ],
        ),
    ]
