# Generated by Django 2.2.5 on 2019-09-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order", "0004_remove_order_fully_paid")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.SmallIntegerField(
                choices=[(0, "Pick Up"), (2, "In House")],
                help_text="Indicates weather the order is a Pick up (0) order or In House (1)",
            ),
        ),
        migrations.AlterField(
            model_name="orderinvite",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Pending"), (1, "Accepted"), (2, "Rejected")],
                default=0,
                help_text="Invite status, 0: Pending, 1: Accep",
            ),
        ),
    ]
