# Generated by Django 2.2.5 on 2019-09-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("order", "0007_auto_20190928_0437")]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item_set",
                to="order.Order",
            ),
        )
    ]
