# Generated by Django 2.2.5 on 2019-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_auto_20191002_1656"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (2, "Canceled"),
                    (1, "Open"),
                    (3, "Checkout"),
                    (4, "Completed"),
                ],
                default=1,
            ),
        ),
    ]
