# Generated by Django 2.2.5 on 2019-10-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(name="order", options={"ordering": ("-id",)},),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.RestaurantTable",
            ),
        ),
    ]
