# Generated by Django 2.2.8 on 2020-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_has_restaurant_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
