# Generated by Django 2.2.3 on 2019-07-20 21:11

from django.db import migrations


def create_groups(apps, schema_editor):
    """
        Create the basic Customer and Restaurant Groups automatically.
    """
    Group = apps.get_model("auth", "group")
    Group.objects.create(name="Customer")
    Group.objects.create(name="Restaurant")


class Migration(migrations.Migration):

    dependencies = [("account", "0001_initial")]

    operations = [migrations.RunPython(create_groups)]
