# Generated by Django 2.2.3 on 2019-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0003_auto_20190809_1129")]

    operations = [
        migrations.RemoveField(model_name="user", name="full_name"),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Users name / Restaurants name",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
