# Generated by Django 2.2.4 on 2019-08-11 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0006_verifyphonetoken_phone_number")]

    operations = [
        migrations.AlterField(
            model_name="verifyphonetoken",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        )
    ]
