# Generated by Django 2.2.4 on 2019-08-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0007_auto_20190811_0703")]

    operations = [
        migrations.RemoveField(model_name="verifyphonetoken", name="phone_number")
    ]
