# Generated by Django 2.2.4 on 2019-08-11 12:01

from django.db import migrations, models
import utils.file


class Migration(migrations.Migration):

    dependencies = [("account", "0009_changephonenumbertoken")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="user/profile-picture/default.jpg",
                upload_to=utils.file.RandomFileName("user/profile-picture/"),
                verbose_name="Profile Picture",
            ),
        )
    ]
