# Generated by Django 2.2.5 on 2019-12-07 10:15

from django.db import migrations, models
import utils.file


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20191201_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user/profile-picture/default.png', null=True, upload_to=utils.file.RandomFileName('user/profile-picture/'), verbose_name='Profile Picture'),
        ),
    ]
