# Generated by Django 2.2.8 on 2020-01-22 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_auto_20200120_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changephonenumbertoken",
            name="new_phone_number",
            field=models.CharField(
                db_index=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits.", regex="\\d{10}"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="changephonenumbertoken",
            name="old_phone_number",
            field=models.CharField(
                db_index=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits.", regex="\\d{10}"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits.", regex="\\d{10}"
                    )
                ],
            ),
        ),
    ]
