from django.utils.translation import ugettext_lazy as _


class NotificationActionType:
    RESTAURANT_NEW_TABLE_ORDER = "RESTAURANT_NEW_TABLE_ORDER"
    RESTAURANT_NEW_PICKUP_ORDER = "RESTAURANT_NEW_PICKUP_ORDER"
    RESTAURANT_NEW_ITEM_IN_ORDER = "RESTAURANT_NEW_ITEM_IN_ORDER"
    RESTAURANT_CHECKOUT_FROM_ORDER = "RESTAURANT_CHECKOUT_FROM_ORDER"
    RESTAURANT_RECEIVED_PAYMENT_FOR_ORDER = "RESTAURANT_RECEIVED_PAYMENT_FOR_ORDER"
    RESTAURANT_TICKET_RESPONSE_FROM_ADMIN = "RESTAURANT_TICKET_RESPONSE_FROM_ADMIN"
    RESTAURANT_TICKET_CLOSED_BY_ADMIN = "RESTAURANT_TICKET_CLOSED_BY_ADMIN"

    CHOICES = (
        (RESTAURANT_NEW_TABLE_ORDER, _("New Table Order")),
        (RESTAURANT_NEW_PICKUP_ORDER, _("New Pickup Order")),
        (RESTAURANT_NEW_ITEM_IN_ORDER, _("New Item In Order")),
        (RESTAURANT_CHECKOUT_FROM_ORDER, _("Checkout From Order")),
        (RESTAURANT_RECEIVED_PAYMENT_FOR_ORDER, _("Received Payment For Order")),
        (RESTAURANT_TICKET_RESPONSE_FROM_ADMIN, _("Ticket Response From Admin")),
        (RESTAURANT_TICKET_CLOSED_BY_ADMIN, _("Ticket Closed By Admin")),
    )
