# Generated by Django 2.2.5 on 2019-11-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
