# Generated by Django 2.2.12 on 2020-07-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20200418_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='app_inhouse_earning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='app_pickup_earning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='app_total_earning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='inhouse_earning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='inhouse_order_cut',
            field=models.DecimalField(decimal_places=3, default=100.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pickup_earning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pickup_order_cut',
            field=models.DecimalField(decimal_places=3, default=100.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_earning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
