# Generated by Django 2.2.12 on 2020-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20200714_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='total_earning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
