# Generated by Django 2.2.12 on 2020-07-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20200714_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauranttable',
            options={'ordering': ('created_at',)},
        ),
    ]
